ec2: Fix --allow-recreate not recreating terminated spot instances.
Until now, `nixops deploy --check --allow-recreate` would fail to
recreate terminated spot instances, instead emitting the error:

    Exception: spot instance request got fulfilled unexpectedly as instance ‘i-0543dd70c68337dea’

This was because `_reset_state()` did not reset the
`self._cached_instance`, and so the `_get_instance()` call in
`create_instance()` would continue to refer to the ID of the disappeared
instance, eventually producing the error.